Update docker-entrypoint

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -55,6 +55,13 @@ ensure_docker_socket_accessible() {
             adduser docker root
         fi
     fi
+    
+    # Test custom sock and if fail then use default
+    if [ "${DOCKER_SOCK}" != "/var/run/docker.sock.test" ]; then
+        if ! su -l docker -s /bin/bash -c "/usr/local/bin/docker -H unix://${DOCKER_SOCK} run hello-world" > /dev/null 2>&1; then
+                DOCKER_SOCK=/var/run/docker.sock
+        fi
+    fi
 }
 
 slugify() {
